### PR TITLE
Added ability to backup cosmosDB

### PR DESCRIPTION
**Pull request by ViacheslavSavinkov**

### CODE REVIEW

**Comment by Shr3ps** [comment]
Thanks for this great contribution!
Can you update the README file too, usage section, with some values for example?

**Comment by ViacheslavSavinkov** [comment]
> Thanks for this great contribution!
> Can you update the README file too, usage section, with some values for example?

Done!

**Review by Shr3ps — APPROVED** [review]

**Comment by ViacheslavSavinkov** [comment]
Thanks @Shr3ps! Can I also ask you to add v4.0.2 tag so we can reference your repo by it?

**Comment by BzSpi** [comment]
Hmmm... I'm a bit late. Using an object type instead of a map for the variable would be great. no ?

**Comment by ViacheslavSavinkov** [comment]
I can make separate PR if you'd like

**Comment by BzSpi** [comment]
Also, we should set predefined values in this block so that we can enforce best practices.

I would be happy to have people opinion on this :)

**Comment by BzSpi** [comment]
@ViacheslavSavinkov Since Terraform does not support optional object attributes in a non experimental mode at the moment and that some attributes are optional, no need to have the object type, but thanks for suggesting.

About the default value, I suggest to have it set to `{type: "Continuous"}` even if this feature is in public preview.

**Comment by ViacheslavSavinkov** [comment]
But default value is 'Periodic' (with 2 free backups).
Making it 'Continuous' will create CosmosDB with paid backup type (which is in public preview) if user won't specify 'Periodic' in `.hcl`.

**Comment by Shr3ps** [comment]
I opened an internal MergeRequest with some improvements we discussed here. It will probably be merged and released tomorrow with a new tag ;)

**Pull request merged**
